name: todotasks
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3 # Para hacer solicitudes HTTP a tu API
  provider: ^6.0.0 # Para manejar el estado de la aplicación
  fl_chart: ^0.70.2 # Para crear gráficos

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
